#!/usr/bin/env -S just --justfile

set windows-shell := ["powershell.exe", "-NoLogo", "-Command"]

just := just_executable() + " -f " + justfile()
stow := "stow --override='.*' --no-folding -d " + justfile_directory()

dpy_ver := "01a13287cbd27819be1c34fa1ddc1b3643d5001b"
dpy_uri := "https://raw.githubusercontent.com/rime/rime-double-pinyin/" + dpy_ver
dic_ver := "2026.06.03"
dic_uri := "https://raw.githubusercontent.com/iDvel/rime-ice/" + dic_ver + "/cn_dicts"

help:
  @{{just}} --list

[windows]
_rime cmd:
  #!powershell.exe

  $files = @("csa.dict.yaml", "csa.schema.yaml", "default.custom.yaml",
      "double_pinyin_flypy.custom.yaml", "imported.dict.yaml", "weasel.custom.yaml",
      "dicts\emoji.txt", "dicts\math.txt", "lua\csa_processor.lua")
  $schemas = @("double_pinyin.schema.yaml","double_pinyin_flypy.schema.yaml")
  $dicts = @("8105.dict.yaml","base.dict.yaml","ext.dict.yaml","others.dict.yaml","tencent.dict.yaml")
  $deployer = "$env:ProgramFiles\Rime\weasel-0.17.4\WeaselDeployer.exe"
  $src = "{{justfile_directory()}}\rime"
  $rime = "$env:APPDATA\Rime"
  $shell = New-Object -ComObject WScript.Shell
  $startup = $shell.SpecialFolders("Startup")
  $link = "$startup\WeaselDeploy.lnk"

  if ("setup" -eq "{{cmd}}") {
    New-Item -Type Directory -Force -Path "$rime\dicts", "$rime\lua" > $null

    foreach ($f in $schemas) {
      Invoke-WebRequest -Uri "{{dpy_uri}}/$f" -OutFile "$rime\$f"
    }

    foreach ($f in $dicts) {
      Invoke-WebRequest -Uri "{{dic_uri}}/$f" -OutFile "$rime\dicts\$f"
    }

    foreach ($f in $files) {
      New-Item -Type SymbolicLink -Path "$rime\$f" -Value "$src\$f" -Force > $null
    }

    $shortcut = $shell.CreateShortcut("$link")
    $shortcut.TargetPath = "{{just_executable()}}"
    $shortcut.Arguments = "-f {{justfile()}} _rime deploy"
    $shortcut.Save()
  }
  elseif ("deploy" -eq "{{cmd}}") {
    $f = "weasel.custom.yaml"

    Remove-Item -Force -ErrorAction Ignore -Path "$rime\$f"
    &"$deployer" /deploy

    Start-Sleep -Seconds 5

    New-Item -Force -Type SymbolicLink -Path "$rime\$f" -Value "$src\$f" > $null
    &"$deployer" /deploy
  }
  else {
    foreach ($f in $files) {
      Remove-Item -Force -ErrorAction Ignore -Path "$rime\$f"
    }
    foreach ($f in $dicts) {
      Remove-Item -Force -ErrorAction Ignore -Path "$rime\dicts\$f"
    }
    foreach ($f in $schemas) {
      Remove-Item -Force -ErrorAction Ignore -Path "$rime\$f"
    }
    Remove-Item -Force -ErrorAction Ignore -Path "$link"
  }

[unix]
_setup_common:
  @{{stow}} -t "${HOME}" common

[windows]
_setup_common:
  #!powershell.exe
  $s = "{{justfile_directory()}}\common\.emacs.d"
  $d = "$env:APPDATA\.emacs.d"
  $f = "init.el"
  New-Item -Type Directory -Force -Path "$d"  > $null
  New-Item -Force -Type SymbolicLink -Path "$d\$f" -Value "$s\$f" > $null

[unix]
_remove_common:
  @{{stow}} -D -t "${HOME}" common

[windows]
@_remove_common:
  Remove-Item -Force -ErrorAction Ignore "$env:APPDATA\.emacs.d\init.el"

[macos]
_setup_darwin:
  @{{stow}} -t "${HOME}" darwin

[macos]
_remove_darwin:
  @{{stow}} -D -t "${HOME}" darwin

[unix]
_setup_server:
  @{{stow}} -t "${HOME}" server

[unix]
_remove_server:
  @{{stow}} -D -t "${HOME}" server

[macos]
_setup_rime:
  #!/bin/sh
  set -eu

  rime="${HOME}/Library/Rime"
  {{stow}} -t "${rime}" rime

  for name in {"double_pinyin","double_pinyin_flypy"}; do
    file="${name}.schema.yaml"
    curl -LSso "${rime}/${file}" "{{dpy_uri}}/${file}"
  done

  for name in {"8105","base","ext","others","tencent"}; do
    file="${name}.dict.yaml"
    curl -LSso "${rime}/dicts/${file}" "{{dic_uri}}/${file}"
  done

[macos]
_remove_rime:
  #!/bin/sh
  set -eu

  rime="${HOME}/Library/Rime"
  {{stow}} -t "${rime}" -D rime

  for name in {"double_pinyin","double_pinyin_flypy"}; do
    rm -f "${rime}/${name}.schema.yaml"
  done

  for name in {"8105","base","ext","others","tencent"}; do
    rm -f "${rime}/dicts/${name}.dict.yaml"
  done

[windows]
_setup_rime: (_rime "setup")

[windows]
_remove_rime: (_rime "remove")

@setup pkg *pkgs:
  {{just}} "_setup_{{pkg}}"
  {{ if pkgs != "" { just + " setup " + pkgs } else { "" } }}

@remove pkg *pkgs:
  {{just}} "_remove_{{pkg}}"
  {{ if pkgs != "" { just + " remove " + pkgs } else { "" } }}
